spring:
 application:
  name: stock-price-service
server:
 port: 8000

 datasource:
  url: jdbc:h2:mem:testdb
  driverClassName: org.h2.Driver
  username: sa
  password:
 jpa:
  database-platform: org.hibernate.dialect.H2Dialect